a=input("enter the value of a :")
b=input("enter the value of b :")
sum=float(a)+float(b)
print("the integral sum is :",sum)
product=float(a)*float(b)
print("integral product is :",product)
subtraction=float(a)-float(b)
print("integral subtraction is :",subtraction)
division=float(a)/float(b)
print("quotient is :",division)
modulus=float(a)%float(b)
print("modulus is :", modulus)
floatdivision=float(a)//float(b) 
print("final value is :",floatdivision)
exponent=float(a)**float(b)
print("exponential value is :",exponent)
addtwo=float(a)+float(b)
print("written vlaue is :",addtwo)
